/*
-- Query: select * from movies
LIMIT 0, 500

-- Date: 2020-10-10 00:06
*/
<<<<<<< HEAD
INSERT INTO `movies` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (337401,0,'/rd7ElSRYhN2CFqMcyH8rqrwLbd6.jpg','Mulan','en','Mulán','El emperador de China emite un decreto para reclutar a un varón por cada familia que deberá servir en el ejército imperial para defender al país de los invasores del norte. Hua Mulán, hija única de un condecorado guerrero, se presenta para evitar que su anciano padre sea llamado a filas. Se hace pas','2020-09-04','');
INSERT INTO `movies` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (340102,0,'/pBWrc52L3NmJLMZwfLzmP61ZO3.jpg','The New Mutants','en','Los nuevos mutantes','Los cinco jóvenes mutantes descubren sus habilidades mientras están recluidos en una instalación secreta contra su voluntad. Juntos, lucharán para escapar de sus pecados pasados y salvarse a sí mismos.','2020-08-26','');
INSERT INTO `movies` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (413518,0,'/7XvaQsCoDW1x8CxPiv7AzQ5OUzX.jpg','Pinocchio','it','Pinocho','Adaptación de la clásica historia del muñeco de madera llamado Pinocho, que desea ser un niño de carne y hueso.','2019-12-19','');
INSERT INTO `movies` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (446893,0,'/lkiYPIuh314llJOHJokvjCPztRb.jpg','Trolls World Tour','en','Trolls 2 Gira mundial','En una aventura que les llevará más allá de todo lo que habían conocido, Poppy y Branch descubren que su tribu de Trolls es solo una de las seis que existen, que el resto están repartidas en seis reinos y consagradas a seis tipos distintos de música: funk, country, tecno, clásica, pop y rock. La rei','2020-03-12','');
INSERT INTO `movies` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (479259,0,'/vQgXwuJrlpzGDI8169tRQRy71Nv.jpg','Lost Girls & Love Hotels','en','I Am Not a Bird','Margaret está haciendo todo lo que está a su alcance para olvidar su hogar, y la vida nocturna exótica de Tokio, repleta de bebidas, drogas y hoteles de amor de tres horas, le permite mantener sus demonios a raya. Trabajando como especialista inglesa en Air-Pro Stewardess Training Institute durante ','2020-09-18','');
INSERT INTO `movies` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (499932,0,'/rIw4e4ZRMznLj21mASBcXIUuOsN.jpg','The Devil All the Time','en','El diablo a todas horas','Ambientada en las zonas rurales del sur de Ohio y Virginia Occidental,  sigue a un elenco de personajes cautivadores y extraños desde el final de la Segunda Guerra Mundial hasta la década de 1960.','2020-09-11','');
INSERT INTO `movies` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (501979,0,'/4V2nTPfeB59TcqJcUfQ9ziTi7VN.jpg','Bill & Ted Face the Music','en','Bill & Ted Face the Music','A dos aspirantes a rockeros de San Dimas, California, se les dijo una vez que salvarían el universo durante una aventura de viaje en el tiempo, pero se encuentran como padres de mediana edad que aún intentan poner en marcha una canción exitosa y cumplir su destino. Sin suerte e inspiración, Bill y T','2020-08-27','');
INSERT INTO `movies` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (528085,0,'/7D430eqZj8y3oVkLFfsWXGRcpEG.jpg','2067','en','2067','El viaje de un hombre hacia el futuro para salvar un mundo moribundo.','2020-10-01','');
INSERT INTO `movies` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (531876,0,'/hPkqY2EMqWUnFEoedukilIUieVG.jpg','The Outpost','en','The Outpost','Narra la historia real de una de las batallas más duras que tuvo lugar durante la guerra de Afganistán. Un pequeño equipo de 53 soldados estadounidenses tuvo que enfrentarse contra más de 400 combatientes talibanes durante la operación llamada “Libertad duradera”... Adaptación del best seller escrit','2020-06-24','');
INSERT INTO `movies` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (539885,0,'/qzA87Wf4jo1h8JMk9GilyIYvwsA.jpg','Ava','en','Ava','Ava es una mortífera asesina a sueldo que trabaja para una organización de operaciones encubiertas, que viaja por todo el mundo acabando con aquellos objetivos que nadie más puede derribar. Cuando uno de sus encargos sale mal, Ava tendrá que luchar por una vida.','2020-07-02','');
INSERT INTO `movies` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (577922,0,'/oh8XmxWlySHgGLlx8QOBmq9k72j.jpg','Tenet','en','Tenet','Una acción épica que gira en torno al espionaje internacional, los viajes en el tiempo y la evolución, en la que un agente secreto debe prevenir la Tercera Guerra Mundial.','2020-08-22','');
INSERT INTO `movies` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (581392,0,'/ew1lAU8yV66JbivBU1Zh4Wj4pOB.jpg','반도','ko','Train To Busan 2: Peninsula','Después de que la infección que se extendió hace 4 años, solo algunas partes de Corea del Sur permanecen resguardadas, aunque la Península de Busan es la única parte en donde pueden buscar refugio los coreanos, muchos aún mantienen la esperanza de ser rescatados por ayuda internacional.','2020-07-15','');
INSERT INTO `movies` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (592350,0,'/2KavuY24PpXBMQ2efbOknKaeYS.jpg','僕のヒーローアカデミア THE MOVIE ヒーローズ：ライジング','ja','My Hero Academia: el despertar de los héroes','Un nuevo villano, llamado Nine, está buscando a Tomura Shigaraki. Para ello, decide atacar la isla de Nabutō. Segunda película de la serie anime \"My Hero Academia\".','2019-12-20','');
INSERT INTO `movies` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (605499,0,'/xIKVeH1iAKJOYYh9lvObD3hYIaf.jpg','Monsoon','en','Monsoon','Kit no recuerda mucho de su Vietnam natal. Cuando regresa a la Tierra de la Estrella Dorada por primera vez en más de treinta años, contempla su entorno local como lo haría cualquier turista occidental, y el entorno es tan exótico como incomprensible el idioma. El objetivo de los viajes de Kit, enco','2020-09-25','');
INSERT INTO `movies` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (613504,0,'/3k4TvOWxJZyeMJtbjHQELKIEhpb.jpg','After We Collided','en','After: en mil pedazos','Ha pasado el tiempo, y Hardin todavía no se sabe si es realmente el chico profundo y reflexivo del que Tessa se enamoró, o ha sido un extraño todo este tiempo. Ella quiere alejarse, pero no es tan fácil. Tessa se ha centrado en sus estudios y comienza a trabajar como becaria en Vance Publishing. All','2020-09-02','');
INSERT INTO `movies` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (619592,0,'/2gPe9cpLGRBbuTKjGBpGkzSGRRP.jpg','Force of Nature','en','La fuerza de la naturaleza','Una banda de ladrones planea un atraco durante un huracán y se encuentra con problemas cuando un policía en desgracia intenta obligar a todos en el edificio a evacuar.','2020-07-02','');
INSERT INTO `movies` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (627290,0,'/kxekf7Ufxhubi00h02oWq6gbkWX.jpg','Antebellum','en','Antebellum','Verónica es una escritora de éxito que queda atrapada en una terrorífica realidad cuyo misterio debe resolver antes de que sea demasiado tarde.','2020-09-02','');
INSERT INTO `movies` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (659986,0,'/gzFatNrw0lhKD5NxaU6zC7S2KjP.jpg','The Owners','en','The Owners','Un grupo de amigos cree que encuentran un blanco fácil en una casa vacía con una caja fuerte llena de dinero en efectivo. Pero cuando la pareja de ancianos que vive allí llega temprano a casa, las cosas cambian de repente. Mientras se produce un juego mortal del gato y el ratón, los posibles ladrone','2020-08-27','');
INSERT INTO `movies` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (694919,0,'/v0BiswYPEZzZTYazvwktPTOTMpP.jpg','Money Plane','en','El avión del dinero','Un ladrón profesional con una deuda de 40 millones de dólares a sus espaldas y la vida de su familia en peligro, se ve obligado a realizar un último golpe: robar un futurista casino aéreo cuya que tiene por clientes a los criminales más peligrosos del mundo.','2020-09-29','');
INSERT INTO `movies` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (726739,0,'/6TtyRxIL0NtVoy7gjaTzmydLpNY.jpg','Cats & Dogs 3: Paws Unite','en','Como perros y gatos: La patrulla unida','A lo largo de una década, la Gran Tregua ha logrado que la hostilidad entre perros y gatos se haya detenido. Merced a esto, Gwen el Gato y Roger el Cánido son 2 agentes secretos que resguardan y salvan el planeta de forma enmascarada sin que los humanos lo descubran. Mas, esta paz se ve conminada en','2020-10-02','');
=======
INSERT INTO `` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (337401,0,'/rd7ElSRYhN2CFqMcyH8rqrwLbd6.jpg','Mulan','en','Mulán','El emperador de China emite un decreto para reclutar a un varón por cada familia que deberá servir en el ejército imperial para defender al país de los invasores del norte. Hua Mulán, hija única de un condecorado guerrero, se presenta para evitar que su anciano padre sea llamado a filas. Se hace pas','2020-09-04','');
INSERT INTO `` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (340102,0,'/pBWrc52L3NmJLMZwfLzmP61ZO3.jpg','The New Mutants','en','Los nuevos mutantes','Los cinco jóvenes mutantes descubren sus habilidades mientras están recluidos en una instalación secreta contra su voluntad. Juntos, lucharán para escapar de sus pecados pasados y salvarse a sí mismos.','2020-08-26','');
INSERT INTO `` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (413518,0,'/7XvaQsCoDW1x8CxPiv7AzQ5OUzX.jpg','Pinocchio','it','Pinocho','Adaptación de la clásica historia del muñeco de madera llamado Pinocho, que desea ser un niño de carne y hueso.','2019-12-19','');
INSERT INTO `` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (446893,0,'/lkiYPIuh314llJOHJokvjCPztRb.jpg','Trolls World Tour','en','Trolls 2 Gira mundial','En una aventura que les llevará más allá de todo lo que habían conocido, Poppy y Branch descubren que su tribu de Trolls es solo una de las seis que existen, que el resto están repartidas en seis reinos y consagradas a seis tipos distintos de música: funk, country, tecno, clásica, pop y rock. La rei','2020-03-12','');
INSERT INTO `` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (479259,0,'/vQgXwuJrlpzGDI8169tRQRy71Nv.jpg','Lost Girls & Love Hotels','en','I Am Not a Bird','Margaret está haciendo todo lo que está a su alcance para olvidar su hogar, y la vida nocturna exótica de Tokio, repleta de bebidas, drogas y hoteles de amor de tres horas, le permite mantener sus demonios a raya. Trabajando como especialista inglesa en Air-Pro Stewardess Training Institute durante ','2020-09-18','');
INSERT INTO `` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (499932,0,'/rIw4e4ZRMznLj21mASBcXIUuOsN.jpg','The Devil All the Time','en','El diablo a todas horas','Ambientada en las zonas rurales del sur de Ohio y Virginia Occidental,  sigue a un elenco de personajes cautivadores y extraños desde el final de la Segunda Guerra Mundial hasta la década de 1960.','2020-09-11','');
INSERT INTO `` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (501979,0,'/4V2nTPfeB59TcqJcUfQ9ziTi7VN.jpg','Bill & Ted Face the Music','en','Bill & Ted Face the Music','A dos aspirantes a rockeros de San Dimas, California, se les dijo una vez que salvarían el universo durante una aventura de viaje en el tiempo, pero se encuentran como padres de mediana edad que aún intentan poner en marcha una canción exitosa y cumplir su destino. Sin suerte e inspiración, Bill y T','2020-08-27','');
INSERT INTO `` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (528085,0,'/7D430eqZj8y3oVkLFfsWXGRcpEG.jpg','2067','en','2067','El viaje de un hombre hacia el futuro para salvar un mundo moribundo.','2020-10-01','');
INSERT INTO `` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (531876,0,'/hPkqY2EMqWUnFEoedukilIUieVG.jpg','The Outpost','en','The Outpost','Narra la historia real de una de las batallas más duras que tuvo lugar durante la guerra de Afganistán. Un pequeño equipo de 53 soldados estadounidenses tuvo que enfrentarse contra más de 400 combatientes talibanes durante la operación llamada “Libertad duradera”... Adaptación del best seller escrit','2020-06-24','');
INSERT INTO `` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (539885,0,'/qzA87Wf4jo1h8JMk9GilyIYvwsA.jpg','Ava','en','Ava','Ava es una mortífera asesina a sueldo que trabaja para una organización de operaciones encubiertas, que viaja por todo el mundo acabando con aquellos objetivos que nadie más puede derribar. Cuando uno de sus encargos sale mal, Ava tendrá que luchar por una vida.','2020-07-02','');
INSERT INTO `` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (577922,0,'/oh8XmxWlySHgGLlx8QOBmq9k72j.jpg','Tenet','en','Tenet','Una acción épica que gira en torno al espionaje internacional, los viajes en el tiempo y la evolución, en la que un agente secreto debe prevenir la Tercera Guerra Mundial.','2020-08-22','');
INSERT INTO `` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (581392,0,'/ew1lAU8yV66JbivBU1Zh4Wj4pOB.jpg','반도','ko','Train To Busan 2: Peninsula','Después de que la infección que se extendió hace 4 años, solo algunas partes de Corea del Sur permanecen resguardadas, aunque la Península de Busan es la única parte en donde pueden buscar refugio los coreanos, muchos aún mantienen la esperanza de ser rescatados por ayuda internacional.','2020-07-15','');
INSERT INTO `` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (592350,0,'/2KavuY24PpXBMQ2efbOknKaeYS.jpg','僕のヒーローアカデミア THE MOVIE ヒーローズ：ライジング','ja','My Hero Academia: el despertar de los héroes','Un nuevo villano, llamado Nine, está buscando a Tomura Shigaraki. Para ello, decide atacar la isla de Nabutō. Segunda película de la serie anime \"My Hero Academia\".','2019-12-20','');
INSERT INTO `` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (605499,0,'/xIKVeH1iAKJOYYh9lvObD3hYIaf.jpg','Monsoon','en','Monsoon','Kit no recuerda mucho de su Vietnam natal. Cuando regresa a la Tierra de la Estrella Dorada por primera vez en más de treinta años, contempla su entorno local como lo haría cualquier turista occidental, y el entorno es tan exótico como incomprensible el idioma. El objetivo de los viajes de Kit, enco','2020-09-25','');
INSERT INTO `` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (613504,0,'/3k4TvOWxJZyeMJtbjHQELKIEhpb.jpg','After We Collided','en','After: en mil pedazos','Ha pasado el tiempo, y Hardin todavía no se sabe si es realmente el chico profundo y reflexivo del que Tessa se enamoró, o ha sido un extraño todo este tiempo. Ella quiere alejarse, pero no es tan fácil. Tessa se ha centrado en sus estudios y comienza a trabajar como becaria en Vance Publishing. All','2020-09-02','');
INSERT INTO `` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (619592,0,'/2gPe9cpLGRBbuTKjGBpGkzSGRRP.jpg','Force of Nature','en','La fuerza de la naturaleza','Una banda de ladrones planea un atraco durante un huracán y se encuentra con problemas cuando un policía en desgracia intenta obligar a todos en el edificio a evacuar.','2020-07-02','');
INSERT INTO `` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (627290,0,'/kxekf7Ufxhubi00h02oWq6gbkWX.jpg','Antebellum','en','Antebellum','Verónica es una escritora de éxito que queda atrapada en una terrorífica realidad cuyo misterio debe resolver antes de que sea demasiado tarde.','2020-09-02','');
INSERT INTO `` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (659986,0,'/gzFatNrw0lhKD5NxaU6zC7S2KjP.jpg','The Owners','en','The Owners','Un grupo de amigos cree que encuentran un blanco fácil en una casa vacía con una caja fuerte llena de dinero en efectivo. Pero cuando la pareja de ancianos que vive allí llega temprano a casa, las cosas cambian de repente. Mientras se produce un juego mortal del gato y el ratón, los posibles ladrone','2020-08-27','');
INSERT INTO `` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (694919,0,'/v0BiswYPEZzZTYazvwktPTOTMpP.jpg','Money Plane','en','El avión del dinero','Un ladrón profesional con una deuda de 40 millones de dólares a sus espaldas y la vida de su familia en peligro, se ve obligado a realizar un último golpe: robar un futurista casino aéreo cuya que tiene por clientes a los criminales más peligrosos del mundo.','2020-09-29','');
INSERT INTO `` (`idMovie`,`adult`,`posterPath`,`originalTitle`,`originalLanguage`,`title`,`overview`,`releaseDate`,`trailerPath`) VALUES (726739,0,'/6TtyRxIL0NtVoy7gjaTzmydLpNY.jpg','Cats & Dogs 3: Paws Unite','en','Como perros y gatos: La patrulla unida','A lo largo de una década, la Gran Tregua ha logrado que la hostilidad entre perros y gatos se haya detenido. Merced a esto, Gwen el Gato y Roger el Cánido son 2 agentes secretos que resguardan y salvan el planeta de forma enmascarada sin que los humanos lo descubran. Mas, esta paz se ve conminada en','2020-10-02','');
>>>>>>> master
